baseURL = "https://rashidakaku.github.io/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "Rashida-Blog"
copyright = "This is a customized copyright."
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Welcome My Blog"
enableGitalk = true
enableGiscus = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "h0tc0oxd6b"

googleSearchCode = "https://cse.google.com/cse?cx=f23090994f28149c4"
favicon = "https://rashida.cab:6901/uploads/2022/12/11/6395b6203c857.jpeg"
enableReadingTime=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Rashida-Blog" # will set 'og:site_name'
description = "Welcome My Blog"  # will set 'og:description'

[params.gitalk]
  owner = "RashidaKAKU"
  repo = "rashidakaku.github.io"
  client_id = "6885baa81532d9c06ace"
  client_secret = "f2827c00095c21b42f98fa18b751ae087c1145c0"
[taxonomies]
   tag = "Tags"
   category = "Categories"

[params.utterances]
repo="BlogDOC"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data-repo="RashidaKAKU/rashidakaku.github.io"
    data-repo-id="R_kgDOJgQAdw"
    data-category-id="DIC_kwDOJgQAd84CWWQE"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="top"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    crossorigin="anonymous"


[[menu.main]]
url = "/categories"
name = "分类"
weight = 1
[[menu.main]]
url = "/tags"
name = "标签"
weight = 2
[[menu.main]]
url = "/posts"
name = "存档"
weight = 3
# [[menu.main]]
# url = "/index.xml"
# name = "RSS"
# weight = 4
